version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: database-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - mynet
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  order-service:
    build: ./Order
    volumes:
      - ./Order:/Order
      - ~/m2:/root/.m2
    working_dir: /Order
    ports:
      - 9191:8000
    command: mvn clean spring-boot:run
    networks:
      - mynet
  inventory-service:
    build: ./Inventory
    volumes:
      - ./Inventory:/Inventory
      - ~/m2:/root/.m2
    working_dir: /Inventory
    ports:
      - 9090:8000
    command: mvn clean spring-boot:run
    networks:
      - mynet
  payment-service:
    build: ./Payment
    volumes:
      - ./Payment:/Payment
      - ~/m2:/root/.m2
    working_dir: /Payment
    ports:
      - 9292:8000
    command: mvn clean spring-boot:run
    networks:
        - mynet
#  keycloak:
#    image: jboss/keycloak:4.8.3.Final
#    restart: on-failure
#    command:
#      - "-b"
#      - "0.0.0.0"
#      - "-Dkeycloak.migration.action=import"
#      - "-Dkeycloak.migration.provider=dir"
#      - "-Dkeycloak.migration.dir=/config/"
#      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
#    volumes:
#      - ./config:/config/
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#      - DB_VENDOR=MYSQL
#      - DB_USER=root
#      - DB_PASSWORD=root
#      - DB_ADDR=database-service
#      - DB_PORT=3306
#      - DB_DATABASE=test
#    ports:
#      - "8888:8080"
#    networks:
#      - mynet
#    depends_on:
#      - database-service